### ISSUE TITLE
wrong width/height ratios due to missing radius

### ISSUE THREAD

**Issue by martin-raden** [ViennaRNA/forna#35]
@j-4 you have to use within `self.centerView = function()`

```
        // Get the bounding box
        minX = d3.min(self.graph.nodes.map(function(d) {return d.x-d.radius;}));
        minY = d3.min(self.graph.nodes.map(function(d) {return d.y-d.radius;}));

        maxX = d3.max(self.graph.nodes.map(function(d) {return d.x+d.radius;}));
        maxY = d3.max(self.graph.nodes.map(function(d) {return d.y+d.radius;}));
```

currently, the `+d.radius` is missing, causing the rendering to cut of half of the nodes for small RNAs.

**Comment by martin-raden** [comment]
given this, you can increase the `minRatio` multiplier to 0.9  ;-)

**Comment by j-4** [comment]
Do you have a patch for that to be able to integrate this?
Or maybe a pull request?

**Comment by martin-raden** [comment]
come on.. I gave you the change in the comment from above... :)

**Comment by j-4** [comment]
Alright then... however, it was in another function ;-)
Thanks a lot for the bug report, it is now fixed in the fornac project and will be included in the next release!
https://github.com/pkerpedjiev/fornac/commit/b5546489da72147da14ea09e05c0ba3a7cc4670e
