### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ko-ala** [ViennaRNA/forna#38]
Hello,

I'm trying to install the program to run locally. However I'm having an issue running it as it says there is a missing module. 
```
Traceback (most recent call last):
  File "forna.py", line 24, in <module>
    import RNA
ImportError: No module named RNA
```
Do you know where this module is located? I've been trying to fix the issue but haven't be successful.

**Comment by j-4** [comment]
Hello!

You need to install the `ViennaRNA` package from here: https://github.com/ViennaRNA/ViennaRNA
Hope this helps! If not, feel free to reopen this issue.

**Comment by ko-ala** [comment]
Thank you for the reply,

I have installed the package and I followed the instructions from here
```
https://www.tbi.univie.ac.at/RNA/documentation.html#install
```

specifically the instructions:

```
tar -zxvf ViennaRNA-2.4.3.tar.gz
cd ViennaRNA-2.4.3
./configure --with-python
make
sudo make install
```

But it still gives me the same error. Am I installing the files in the wrong directory? Thanks again for the help

**Comment by waldeyr** [comment]
Usually, when you install ViennaRNA, the libs go to /usr/local/{bin,lib}
Did you see if, after installation, they are there?

**Comment by ko-ala** [comment]
I've looked but its the list of programs on the documentation here
```
https://www.tbi.univie.ac.at/RNA/documentation.html
```
So a lot of RNA* like RNAcofold and RNApaln but not RNA specifically

**Comment by j-4** [comment]
https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/scripting.html

This is the documentation to look at. You need the Python SWIG Wrapper of the `ViennaRNA` package and not a specific binary. 

To see if the installation of the python interface worked you can try this command:
```
python -c 'import RNA'
```

If it returns nothing, everything is installed and ready. Otherwise you have to check the system variables of your system. Additionally, make sure you are using the right python version. If you use python 3, you need to run `./configure --with-python3`

Good luck!

**Comment by ko-ala** [comment]
Thank you for all the help. The interfaces were not being installed so I guess I'll have to check the system variables.

Thank you!

**Comment by ko-ala** [comment]
Hi again,

So I had thought I resolved this isssue as ``` ./configure --with-python``` returned the following
```
##############################################
# Files will be installed in the following  ##
# directories:                              ##
##############################################

  Executables:        /usr/local/bin
  Libraries:          /usr/local/lib
  Header files:       /usr/local/include
  Extra Data:         /usr/local/share
  Man pages:          /usr/local/share/man
  Documentation:      /usr/local/share/doc/ViennaRNA
    (HTML):           /usr/local/share/doc/ViennaRNA/html
    (PDF):            /usr/local/share/doc/ViennaRNA
  Perl5 Interface:    Not to be installed
    (binaries):       
    (scripts):        
  Python2 Interface:  
    (binaries):       /usr/local/lib/python2.7/site-packages
    (scripts):        /usr/local/lib/python2.7/site-packages
  Python3 Interface:  Not to be installed
    (binaries):       
    (scripts): 
```

but the RNA module is still missing. Is there anything in the installation that I should check again for errors? Thank you for the help

**Comment by j-4** [comment]
Hello,

Can you please post the output of the following commands:
```
python --version
python -c 'import sys; print(sys.path)'
RNAfold --version
python -c 'import RNA; print(RNA.__version__)'
```

**Comment by ko-ala** [comment]
the outputs are:

```
Python 2.7.12

['', '/usr/local/lib/python2.7/dist-packages/forgi-1.0-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/ethan/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

RNAfold 2.4.3

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named RNA
```

**Comment by j-4** [comment]
mhmm... could be a problem related to https://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages
Please also post:
```
whereis RNAfold
ls -alh /usr/local/lib/python2.7/site-packages/
ls -alh /usr/local/lib/python2.7/dist-packages/
```

**Comment by ko-ala** [comment]
these are the output:

```
RNAfold: /usr/local/bin/RNAfold

total 16M
drwxrwsr-x 3 root staff 4.0K Jan 25 09:19 .
drwxrwsr-x 4 root staff 4.0K Jan 22 22:54 ..
drwxr-sr-x 2 root staff 4.0K Jan 25 09:19 RNA
-rwxr-xr-x 1 root staff  16M Jan 25 09:19 _RNA.so

total 256K
drwxrwsr-x 24 root staff 4.0K Jan 23 23:02 .
drwxrwsr-x  4 root staff 4.0K Jan 22 22:54 ..
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 builtins
-rw-r--r--  1 root staff  925 Jan 22 23:06 config-0.3.9.egg-info
-rw-r--r--  1 root staff  56K May 11  2010 config.py
-rw-r--r--  1 root staff  57K Jan 22 23:06 config.pyc
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 copyreg
drwxr-sr-x  2 root staff 4.0K Jan 23 23:01 decorator-4.2.1.dist-info
-rw-r--r--  1 root staff  17K Jan 23 23:01 decorator.py
-rw-r--r--  1 root staff  15K Jan 23 23:01 decorator.pyc
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 _dummy_thread
-rw-r--r--  1 root staff  217 Jan 20 17:23 easy-install.pth
drwxr-sr-x  4 root staff 4.0K Jan 23 23:02 forgi-1.0-py2.7.egg
drwxr-sr-x  9 root staff 4.0K Jan 20 17:25 future
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 future-0.16.0.egg-info
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 html
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 http
drwxr-sr-x  3 root staff 4.0K Jan 20 17:25 libfuturize
drwxr-sr-x  3 root staff 4.0K Jan 20 17:25 libpasteurize
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 _markupbase
drwxr-sr-x 11 root staff 4.0K Jan 23 23:01 networkx
drwxr-sr-x  2 root staff 4.0K Jan 23 23:01 networkx-2.1.egg-info
drwxr-sr-x  7 root staff 4.0K Jan 20 17:25 past
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 queue
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 reprlib
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 socketserver
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 _thread
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 tkinter
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 winreg
drwxr-sr-x  2 root staff 4.0K Jan 20 17:25 xmlrpc
```

**Comment by j-4** [comment]
Ok, now its clear. `ViennaRNA` is installed in `/usr/local/lib/python2.7/site-packages/` and not `dist-packages`, which might be a bug. (@RaumZeit ?)
As a workaround, add `/usr/local/lib/python2.7/site-packages/` to your `sys.path` which can be done as described here: https://superuser.com/questions/247620/how-to-globally-modify-the-default-pythonpath-sys-path

**Comment by RaumZeit** [comment]
I'd say, no bug in ViennaRNA, but maybe a bug in Debian/Ubuntu.
What's the output of
```
python -c "import distutils.sysconfig; print(distutils.sysconfig.get_python_lib())"
```
It should point to `dist-packages` if python is configured properly. If it is `site-packages` which doesn't seem to be in your python path, then this is a bug in your Linux distribution and how it sets up the python package.

P.S.: As far as I understand, debian/ubuntu use the `dist-packages` directory for everything that is installed via apt-get. Packages that are installed systemwide from source should use the `site-packages` directory. So, maybe the installation is still alright but the `sys.path` variable is not set up properly?

**Comment by j-4** [comment]
Thanks @RaumZeit ! So it really seems like a bug in your distribution!

Because of packages installed from source: The [Debian wiki](https://wiki.debian.org/Python#Deviations_from_upstream) is a little controversy there. First line says, that 
> Third party Python software installed from Debian packages goes into dist-packages, not site-packages... 

So ok, this is for dep packages then. So code built from source goes into `site-lackages`? Might be, but not written there...  It also says that
> distutils setup scripts install files in /usr/local/ [...]. Note that /usr/local/lib/pythonX.Y/dist-packages is in sys.path so that modules **not installed from Debian packages** can still be accessed by the system Python

So it actually seems as if modules built from source should go to `/usr/local/lib/pythonX.Y/dist-packages`?! Stupid Debian convention... this regulation seems quite artificial!

**Comment by ko-ala** [comment]
Thanks! The error's been resolved.
